import { Time } from "../../../shared/time";
import { ExcelRebateFile } from "../items/ExcelRebateFile";
import { FileStore } from "./FileStore";

/** ------------------------------------------------------------------------- */

interface Meta { quarter: Time }

export class OutputFile extends ExcelRebateFile {
  meta: Meta;
  constructor(path: string, meta: Meta) { super(path); this.meta = meta; }
}

/** ------------------------------------------------------------------------- */

/**
 * Holds the resulting omni-Excel file which is generated by combining all
 * rebates in the DestinationStore.
 */
export class OutputStore extends FileStore<OutputFile> {
  public readonly name = "outputs";

  public async gather(): Promise<void> {
    for (const [time_path, time_str] of await FileStore.getSubFolders(this.directory)) {
      const time = Time.parse(time_str);
      if (time == null) continue;

      for (const [file_path] of await FileStore.getSubFiles(time_path)) {
        this.add(new OutputFile(file_path, { quarter: time }));
      }
    }
  }
}